[build]
  builder = "DOCKERFILE"
  dockerfilePath = "./RustIDE.Server/Dockerfile"

[deploy]
  startCommand = "dotnet RustIDE.Server.dll" # команда для запуска, если требуется
  numReplicas = 1
  region = "us-west1" # укажите регион, если необходимо
  restartPolicyType = "ALWAYS"  # Политика перезапуска
  healthcheckPath = "/health"  # Путь для проверки состояния